version: '3.1'
services:

  # MySql database
  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: vs4dds4sd4ss6sd88daa2
      MYSQL_USER: springuser
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: iotMonitorDB
    ports:
      - 3300:3306

  # Service registry
  registry:
    build: ./vue-backend-registry
    restart: always
    network_mode: "host"
    depends_on:
      - database

  # REST Api gateway service
  gateway:
    build: ./vue-backend-gateway
    restart: always 
    network_mode: "host"
    depends_on:
      - database
  
  # Auth service
  auth:
    build: ./vue-backend-auth
    restart: always
    network_mode: "host"
    depends_on:
      - database

  # REST Api resources service
  resources:
    build: ./vue-backend-resources
    restart: always
    network_mode: "host"
    depends_on:
      - database

  # Websocket Service
  websocket:
    build: ./vue-backend-websockets
    restart: always
    network_mode: "host"
    depends_on:
      - database

  # A tomcat servlet which contains the vue app
  webserver:
    build: ./vue-webapp
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
