version: '3.1'
services:
  # MySql database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
      MYSQL_USER: springuser
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: testDB
    ports:
      - 3306:3306
  
  # Login service
  backend:
    build: ./vue-backend-auth
    restart: always
    ports:
      - 8091:8091

  # REST Api recurces service
  backend:
    build: ./vue-backend-resources
    restart: always
    ports:
      - 8090:8090

  # Websocket Service
  backend:
    build: ./vue-backend-resources
    restart: always
    ports:
      - 8090:8090

  # A tomcat servlet which contains the vue app
  webserver:
    build: ./vue-webapp
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - backend
