version: '3.1'
services:

  # MySql database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
      MYSQL_USER: springuser
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: iotMonitorDB
    ports:
      - 3300:3306

  # Service registry
  registry:
    build: ./vue-backend-registry
    restart: always
    depends_on:
      - database

  # REST Api gateway service
  gateway:
    build: ./vue-backend-gateway
    restart: always 
    ports:
      - 8090:8090
    depends_on:
      - database
  
  # Auth service
  auth:
    build: ./vue-backend-auth
    restart: always
    depends_on:
      - database

  # REST Api resources service
  resources:
    build: ./vue-backend-resources
    restart: always
    depends_on:
      - database

  # Websocket Service
  websocket:
    build: ./vue-backend-websockets
    restart: always
    depends_on:
      - database

  # A tomcat servlet which contains the vue app
  webserver:
    build: ./vue-webapp
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
