version: '3.1'
services:
  database:
   image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
      MYSQL_USER: springuser
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: testDB
  app:
    build: ./vue-backed
    restart: false
    ports:
      - 8090:8090
    depends_on:
      - database
  rabbitmq:
    build: rabbitmq
    restart: always